services:
  db:
    image: mysql:8.0
    container_name: secure_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - appnet

  web:
    build: ./web
    container_name: secure_web
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - appnet
    user: "1001:1001"  # Run as non-root user

volumes:
  db_data:

networks:
  appnet: